<?$APPLICATION->IncludeComponent(
	"bitrix:form.result.new",
	"contacts",
	Array(
	"AJAX_MODE" => "Y",
	"AJAX_OPTION_HISTORY" => "N",
	"AJAX_OPTION_JUMP" => "N",
	"AJAX_OPTION_SHADOW" => "N",
	"AJAX_OPTION_STYLE" => "N",
	"CACHE_TIME" => "3600",
	"CACHE_TYPE" => "A",
	"CHAIN_ITEM_LINK" => "",
	"CHAIN_ITEM_TEXT" => "",
	"COMPONENT_TEMPLATE" => "contacts",
	"COMPOSITE_FRAME_MODE" => "A",
	"COMPOSITE_FRAME_TYPE" => "AUTO",
	"EDIT_URL" => "",
	"IGNORE_CUSTOM_TEMPLATE" => "N",
	"LIST_URL" => "",
	"SEF_MODE" => "N",
	"SUCCESS_URL" => "",
	"USE_EXTENDED_ERRORS" => "Y",
	"WEB_FORM_ID" => "#FORM_ID#",
	"VARIABLE_ALIASES" => array("WEB_FORM_ID"=>"WEB_FORM_ID","RESULT_ID"=>"RESULT_ID",),
	"PREDEFINED_VALUES" => $arParams["PREDEFINED_VALUES"],
	)
);?>
